name: Deploy Valid Plus Live

on:
  push:
    branches:
      - live  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/container/validplus

            echo "Pulling latest code..."
            git pull origin live

            echo "Building Docker image..."
            docker build -t validplus-app .

            echo "Stopping old container..."
            docker stop upbeat_mccarthy || true
            docker rm upbeat_mccarthy || true

            echo "Running new container..."
            docker run -d --name upbeat_mccarthy -p 8000:80 validplus-app

            echo "Deployment complete!"
