name: Deploy FastAPI App

on:
  push:
    branches:
      - live  # Runs on push to the 'live' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the latest code from the live branch
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code in the repository

      # Step 2: Deploy to the server using SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master  # SSH into the server and deploy
        with:
          host: 66.42.92.38  # Replace with your server's IP address
          username: root  # Use your server's username
          password: C!4e8),mCaseKAj7  # Use your server's password or SSH key
          script: |
            # Step 3: Change to the project directory
            cd ~/container/validplus  # Path to your FastAPI project directory

            # Step 4: Pull the latest code from the live branch
            echo "Pulling latest code..."
            git pull origin live

            # Step 5: Stop the old FastAPI app (Uvicorn process)
            echo "Stopping old FastAPI app..."
            pkill -f "uvicorn main:app" || true  # Kill any existing uvicorn processes

            # Step 6: Start the new FastAPI app
            echo "Starting FastAPI app..."
            source venv/bin/activate  # Activate the virtual environment
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &  # Run Uvicorn in the background

            # Step 7: Reload Nginx to apply any changes
            echo "Reloading Nginx..."
            sudo systemctl reload nginx  # Reload Nginx to apply any changes

            # Step 8: Confirm deployment is complete
            echo "Deployment complete!"
