name: Deploy Valid Plus Live

on:
  push:
    branches:
      - live  # Triggers the workflow on push to the 'live' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # SSH into the server to deploy
        with:
          host: 66.42.92.38  # Your server's IP address
          username: root  # Your server's username
          password: C!4e8),mCaseKAj7 
          script: |
            echo "Starting deployment process..."
            
            # Navigate to FastAPI app directory
            cd ~/container/validplus

            # Pull the latest changes from the 'live' branch
            echo "Pulling latest code..."
            git fetch origin
            git checkout live
            git pull origin live

            # Stop any running FastAPI app
            echo "Stopping old FastAPI app..."
            pkill -f "uvicorn main:app" || true  # Gracefully stop any running FastAPI app (if any)

            # Activate virtual environment
            echo "Activating virtual environment..."
            source venv/bin/activate

            # Install requirements in case they are updated
            echo "Installing dependencies..."
            pip install -r requirements.txt

            # Start the new FastAPI app with Uvicorn in the background
            echo "Starting new FastAPI app..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &

            # Optionally, reload Nginx if you are using it to proxy
            echo "Reloading Nginx..."
            sudo systemctl reload nginx

            echo "Deployment complete! FastAPI app is now live."

