name: Deploy Valid Plus Live

on:
  push:
    branches:
      - live  # Triggers the workflow on push to the 'live' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # SSH into the server to deploy
        with:
          host: 66.42.92.38  # Your server's IP address
          username: root  # Your server's username
          password: C!4e8),mCaseKAj7 
          script: |
            cd ~/container/validplus  # Change directory to where your FastAPI app is located

            echo "Pulling latest code..."
            git pull origin live  # Pull the latest code from the 'live' branch

            echo "Stopping old FastAPI app..."
            # Gracefully kill the old FastAPI app if it's running
            pkill -f 'uvicorn' || true  # Kill any old uvicorn process
            sleep 3  # Wait a few seconds for the process to fully terminate

            echo "Starting new FastAPI app..."
            # Run the FastAPI app in the background using nohup
            nohup /root/container/validplus/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload > /root/container/validplus/uvicorn.log 2>&1 &

            echo "Deployment complete!"  # Notify that deployment is done

            # Optionally: Check if the FastAPI app is running and respond accordingly
            if ps aux | grep -v grep | grep uvicorn; then
              echo "FastAPI app is running!"
            else
              echo "FastAPI app failed to start!"
            fi
