name: Deploy Valid Plus Live

on:
  push:
    branches:
      - live  # Triggers the workflow on push to the 'live' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # SSH into the server to deploy
        with:
          host: 66.42.92.38  # Your server's IP address
          username: root  # Your server's username
          password: C!4e8),mCaseKAj7
          script: |
            cd ~/container/validplus  # Change directory to where your FastAPI app is located

            echo "Pulling latest code..."
            git pull origin live  # Pull the latest code from the 'live' branch

            echo "Stopping old FastAPI app..."
            # Gracefully stop the existing FastAPI process by killing the running uvicorn processes
            pkill -f 'uvicorn' || true  # Stop any running FastAPI app (if any)
            sleep 5  # Give some time for processes to fully terminate

            # Check if there are any lingering uvicorn processes and kill them again if necessary
            if ps aux | grep -v grep | grep uvicorn; then
              pkill -f 'uvicorn'  # Ensure it is fully terminated
              sleep 5
            fi

            echo "Starting new FastAPI app..."
            # Run FastAPI with uvicorn in the background, capturing logs for debugging
            nohup /root/container/validplus/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload > /root/container/validplus/uvicorn.log 2>&1 &

            # Verify that FastAPI is running
            echo "Verifying if FastAPI app is running..."
            if ps aux | grep -v grep | grep uvicorn; then
              echo "FastAPI app is successfully running!"
            else
              echo "FastAPI app failed to start!"
              exit 1  # Exit with failure code to notify of a failed deployment
            fi

            echo "Deployment complete!"  # Notify that deployment was successful
