name: Deploy Valid Plus Live

on:
  push:
    branches:
      - live  # Triggers the workflow on push to the 'live' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the latest code from the repo

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # SSH into the server to deploy
        with:
          host: 66.42.92.38  # Your server's IP address
          username: root  # Your server's username
          password: C!4e8),mCaseKAj7 
          script: |
            cd ~/container/validplus  # Change directory to where your FastAPI app is located

            echo "Pulling latest code..."
            git pull origin live  # Pull the latest code from the 'live' branch

            echo "Stopping old FastAPI app..."
            # Gracefully kill the old FastAPI process if running
            pkill -f 'uvicorn' || true  # Ensure any old uvicorn process is terminated

            # Optional: Wait for the old process to die gracefully before starting the new one
            sleep 5

            echo "Starting new FastAPI app..."
            # Start the new FastAPI app
            nohup /root/container/validplus/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload > /root/container/validplus/uvicorn.log 2>&1 &

            echo "Deployment complete!"  # Print a message once the deployment is done
